### ISSUE TITLE
ImportError: DLL load failed: The specified procedure could not be found

### ISSUE THREAD

**Issue by bigboss97** [iPERDance/iPERCore#30]
I tried to run the demo:

`(venv) PS E:\bin\iPERCore-main> python demo/motion_imitate.py --gpu_ids 0 --image_size 512 --num_source 2 --output_dir "./results" --assets_dir "./assets" --model_id   "axing_1" --src_path   "path?=./assets/samples/sources/axing_1,name?=axing_1" --ref_path   "path?=./assets/samples/references/bantangzhuyi_1.mp4,name?=bantangzhuyi_1,pose_fc?=300"`

and got following error. What did I miss?

primitives_dir: ./results\primitives\bantangzhuyi_1
processed_dir: ./results\primitives\bantangzhuyi_1\processed
vid_info_path: ./results\primitives\bantangzhuyi_1\processed\vid_info.pkl
-------------------------------------------------------
Process PreprocessConsumer_0:
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\envs\venv\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "e:\bin\ipercore-main\iPERCore\services\preprocess.py", line 41, in run
    device=device
  File "e:\bin\ipercore-main\iPERCore\tools\processors\preprocessors.py", line 125, in __init__
    device=device
  File "e:\bin\ipercore-main\iPERCore\tools\human_mattors\__init__.py", line 11, in build_mattor
    from .point_render_parser import PointRenderGCAMattor
  File "e:\bin\ipercore-main\iPERCore\tools\human_mattors\point_render_parser.py", line 16, in <module>
    from mmdet.apis import init_detector, inference_detector
  File "C:\ProgramData\Miniconda3\envs\venv\lib\site-packages\mmdet\apis\__init__.py", line 1, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "C:\ProgramData\Miniconda3\envs\venv\lib\site-packages\mmdet\apis\inference.py", line 7, in <module>
    from mmcv.ops import RoIPool
  File "C:\ProgramData\Miniconda3\envs\venv\lib\site-packages\mmcv\ops\__init__.py", line 1, in <module>
    from .bbox import bbox_overlaps
  File "C:\ProgramData\Miniconda3\envs\venv\lib\site-packages\mmcv\ops\bbox.py", line 3, in <module>
    ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])
  File "C:\ProgramData\Miniconda3\envs\venv\lib\site-packages\mmcv\utils\ext_loader.py", line 11, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "C:\ProgramData\Miniconda3\envs\venv\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed: The specified procedure could not be found.
                Pre-processing: digital deformation start...
Process HumanDigitalDeformConsumer_0:
Traceback (most recent call last):
  File "e:\bin\ipercore-main\iPERCore\services\preprocess.py", line 136, in run
    prepared_inputs = self.prepare_inputs_for_run_cloth_smpl_links(process_info)
  File "e:\bin\ipercore-main\iPERCore\services\preprocess.py", line 210, in prepare_inputs_for_run_cloth_smpl_links
    src_infos = process_info.convert_to_src_info(self.opt.num_source)
  File "e:\bin\ipercore-main\iPERCore\services\options\process_info.py", line 140, in convert_to_src_info
    src_infos = read_src_infos(self.vid_infos, num_source)
  File "e:\bin\ipercore-main\iPERCore\services\options\process_info.py", line 233, in read_src_infos
    pad_ids = np.random.choice(src_ids, need_pad)
  File "mtrand.pyx", line 908, in numpy.random.mtrand.RandomState.choice
ValueError: 'a' cannot be empty unless no samples are taken

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\envs\venv\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "e:\bin\ipercore-main\iPERCore\services\preprocess.py", line 153, in run
    except Exception("model error!") as e:
TypeError: catching classes that do not inherit from BaseException is not allowed
                Pre-processing: digital deformation completed...
the current number of sources are 1, while the pre-defined number of sources are 2.
        Pre-processing: failed...

**Comment by piaozhx** [comment]
Looks like this error comes from `mmcv`, can you provide details of the installation process of `mmcv`?

**Comment by bigboss97** [comment]
Thanks for the response. I did:
```
(venv) PS C:\Users\home> pip install mmcv
Collecting mmcv
  Downloading mmcv-1.2.3.tar.gz (216 kB)
     |████████████████████████████████| 216 kB 2.2 MB/s
Requirement already satisfied: addict in c:\programdata\miniconda3\envs\venv\lib\site-packages (from mmcv) (2.4.0)
Requirement already satisfied: numpy in c:\programdata\miniconda3\envs\venv\lib\site-packages (from mmcv) (1.19.3)
Requirement already satisfied: Pillow in c:\programdata\miniconda3\envs\venv\lib\site-packages (from mmcv) (8.0.1)
Requirement already satisfied: pyyaml in c:\programdata\miniconda3\envs\venv\lib\site-packages (from mmcv) (5.3.1)
Requirement already satisfied: yapf in c:\programdata\miniconda3\envs\venv\lib\site-packages (from mmcv) (0.30.0)
Requirement already satisfied: regex in c:\programdata\miniconda3\envs\venv\lib\site-packages (from mmcv) (2020.11.13)
Building wheels for collected packages: mmcv
  Building wheel for mmcv (setup.py) ... done
  Created wheel for mmcv: filename=mmcv-1.2.3-py2.py3-none-any.whl size=319484 sha256=408aab1b578bfb50b6089b49d65dcbeb13261d7bcf50aee832184258324c08f6
  Stored in directory: c:\users\home\appdata\local\pip\cache\wheels\b9\4e\88\b1423b7ff0fb534e49dee4a7f423f0f17093939638c50e75a2
Successfully built mmcv
Installing collected packages: mmcv
Successfully installed mmcv-1.2.3
```

and now I'm getting:
```
Process PreprocessConsumer_0:
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\envs\venv\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "e:\bin\ipercore-main\iPERCore\services\preprocess.py", line 41, in run
    device=device
  File "e:\bin\ipercore-main\iPERCore\tools\processors\preprocessors.py", line 125, in __init__
    device=device
  File "e:\bin\ipercore-main\iPERCore\tools\human_mattors\__init__.py", line 11, in build_mattor
    from .point_render_parser import PointRenderGCAMattor
  File "e:\bin\ipercore-main\iPERCore\tools\human_mattors\point_render_parser.py", line 16, in <module>
    from mmdet.apis import init_detector, inference_detector
  File "C:\ProgramData\Miniconda3\envs\venv\lib\site-packages\mmdet\__init__.py", line 1, in <module>
    import mmcv
  File "C:\ProgramData\Miniconda3\envs\venv\lib\site-packages\mmcv\__init__.py", line 4, in <module>
    from .fileio import *
  File "C:\ProgramData\Miniconda3\envs\venv\lib\site-packages\mmcv\fileio\__init__.py", line 4, in <module>
    from .io import dump, load, register_handler
  File "C:\ProgramData\Miniconda3\envs\venv\lib\site-packages\mmcv\fileio\io.py", line 4, in <module>
    from ..utils import is_list_of, is_str
  File "C:\ProgramData\Miniconda3\envs\venv\lib\site-packages\mmcv\utils\__init__.py", line 36, in <module>
    from .parrots_jit import jit, skip_no_elena, skip_no_parrots
  File "C:\ProgramData\Miniconda3\envs\venv\lib\site-packages\mmcv\utils\parrots_jit.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
```

**Comment by anguoKuang** [comment]
> Looks like this error comes from `mmcv`, can you provide details of the installation process of `mmcv`?

请问一下，我已经安装mmcv-full=1.1.5了，运行时报：
Traceback (most recent call last):
  File "A:\Anaconda\envs\IPERcore-main\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "A:\py_workspace\iPERCore-main2\iPERCore-main\iPERCore\services\preprocess.py", line 41, in run
    device=device
  File "A:\py_workspace\iPERCore-main2\iPERCore-main\iPERCore\tools\processors\preprocessors.py", line 125, in __init__
    device=device
  File "A:\py_workspace\iPERCore-main2\iPERCore-main\iPERCore\tools\human_mattors\__init__.py", line 11, in build_mattor
    from .point_render_parser import PointRenderGCAMattor
  File "A:\py_workspace\iPERCore-main2\iPERCore-main\iPERCore\tools\human_mattors\point_render_parser.py", line 16, in <module>
    from mmdet.apis import init_detector, inference_detector
  File "A:\Anaconda\envs\IPERcore-main\lib\site-packages\mmdet\apis\__init__.py", line 1, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "A:\Anaconda\envs\IPERcore-main\lib\site-packages\mmdet\apis\inference.py", line 7, in <module>
    from mmcv.ops import RoIPool
  File "A:\Anaconda\envs\IPERcore-main\lib\site-packages\mmcv\ops\__init__.py", line 1, in <module>
    from .bbox import bbox_overlaps
  File "A:\Anaconda\envs\IPERcore-main\lib\site-packages\mmcv\ops\bbox.py", line 3, in <module>
    ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])
  File "A:\Anaconda\envs\IPERcore-main\lib\site-packages\mmcv\utils\ext_loader.py", line 11, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "A:\Anaconda\envs\IPERcore-main\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed: 找不到指定的程序。


我又通过pip install mmcv ,但是报错：
A:\py_workspace\iPERCore-main2\iPERCore-main>pip install mmcv
Collecting mmcv
  Downloading mmcv-1.2.4.tar.gz (216 kB)
     |████████████████████████████████| 216 kB 31 kB/s
    ERROR: Command errored out with exit status 1:
     command: 'a:\anaconda\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-ov
p1jp3r\\mmcv\\setup.py'"'"'; __file__='"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-ovp1jp3r\\mmcv\\setup.py'"'"';f=getattr(tokenize, '"'"'
open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-ba
se 'C:\Users\ADMINI~1\AppData\Local\Temp\pip-pip-egg-info-6yam5g9f'
         cwd: C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-ovp1jp3r\mmcv\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-ovp1jp3r\mmcv\setup.py", line 10, in <module>
        if torch.__version__ == 'parrots':
    AttributeError: module 'torch' has no attribute '__version__'
    ----------------------------------------
请问一下怎么解决呀

**Comment by piaozhx** [comment]
1. 把你现在安装的mmcv全部卸载掉
2. 到https://download.openmmlab.com/mmcv/dist/index.html 下载你所需要的mmcv 1.1.5 的windows预编译版本

e.g.  pytorch1.6.0 + cuda10.2 + python3.7  就下载mmcv_full-1.1.5+torch1.6.0+cu102-cp37-cp37m-win_amd64.whl这个包安装(注意后缀里有win_amd64这个字段, 不要下载linux版本)

**Comment by anguoKuang** [comment]
> 1. 把你现在安装的mmcv全部卸载掉
> 2. 到https://download.openmmlab.com/mmcv/dist/index.html 下载你所需要的mmcv 1.1.5 的windows预编译版本
> 
> e.g. pytorch1.6.0 + cuda10.2 + python3.7 就下载mmcv_full-1.1.5+torch1.6.0+cu102-cp37-cp37m-win_amd64.whl这个包安装(注意后缀里有win_amd64这个字段, 不要下载linux版本)

没有torch1.7版本的吗？如果我安装mmcv1.6版本的，会导致AssertionError:torch not compiled with cuda enabled错误，我把torch升到1.7又会导致mmcv找不到（ImportError: DLL load failed: 找不到指定的程序）；我把mmcv换成1.5，torch换成1.5，又会导致 import neural_renderer.cuda.load_textures as load_textures_cuda
ImportError: DLL load failed: 找不到指定的程序。

好绝望啊

**Comment by bigboss97** [comment]
I've installed mmcv==1.1.5
```
(venv) PS E:\bin\iPERCore-main> pip show mmcv
Name: mmcv
Version: 1.1.5
Summary: OpenMMLab Computer Vision Foundation
Home-page: https://github.com/open-mmlab/mmcv
Author: MMCV Authors
Author-email: openmmlab@gmail.com
License: UNKNOWN
Location: c:\programdata\miniconda3\envs\venv\lib\site-packages
Requires: opencv-python, yapf, addict, pyyaml, regex, numpy
```
I'm getting:
```
  File "C:\ProgramData\Miniconda3\envs\venv\lib\site-packages\mmcv\utils\ext_loader.py", line 11, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "C:\ProgramData\Miniconda3\envs\venv\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed: The specified procedure could not be found.
                Pre-processing: digital deformation start...
```

**Comment by piaozhx** [comment]
@anguoKuang @bigboss97 We have fixed some bugs on Windows, you can remove the old environment (conda or venv) and try the latest version (Recommend CUDA10.2 + Python3.8.8 + VS2019)

**Comment by bigboss97** [comment]
> 
> 
> @anguoKuang @bigboss97 We have fixed some bugs on Windows, you can remove the old environment (conda or venv) and try the latest version (Recommend CUDA10.2 + Python3.8 + VS2019)

Great, it's progressing, but still not working. Thanks for your work.
I received this error during env setup:
```
  Building wheel for mmpycocotools (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\ProgramData\Miniconda3\envs\venv\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\home\\AppData\\Local\\Temp\\pip-install-tjm06jmd\\mmpycocotools\\setup.py'"'"'; __file__='"'"'C:\\Users\\home\\AppData\\Local\\Temp\\pip-install-tjm06jmd\\mmpycocotools\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\home\AppData\Local\Temp\pip-wheel-vk47qgpx'

*snip*
  c1: fatal error C1083: Cannot open source file: 'pycocotools/_mask.c': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.24.28314\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for mmpycocotools
  Running setup.py clean for mmpycocotools
Successfully built mmdet
Failed to build mmpycocotools
Installing collected packages: cython, mmpycocotools, terminaltables, mmdet
```
I ignored that and ran my own sample:
![Screenshot - 21-01-06 13 57 15](https://user-images.githubusercontent.com/34834507/103724034-8b8aad00-5027-11eb-946f-7e84d294f93f.png)
This looks like a success:
![Screenshot - 21-01-06 13 54 17](https://user-images.githubusercontent.com/34834507/103724063-9f361380-5027-11eb-9da8-47134bea3931.png)
But the result is empty:
![Screenshot - 21-01-06 13 56 16](https://user-images.githubusercontent.com/34834507/103724126-bffe6900-5027-11eb-9ebe-aabe31677e1f.png)
All images are also empty:
![Screenshot - 21-01-06 14 03 57](https://user-images.githubusercontent.com/34834507/103724304-17043e00-5028-11eb-96c0-8925e7483e19.png)

**Comment by Datadelete10426** [comment]
> 1. 把你现在安装的mmcv全部卸载掉
> 2. 到https://download.openmmlab.com/mmcv/dist/index.html 下载你所需要的mmcv 1.1.5 的windows预编译版本
> 
> e.g. pytorch1.6.0 + cuda10.2 + python3.7 就下载mmcv_full-1.1.5+torch1.6.0+cu102-cp37-cp37m-win_amd64.whl这个包安装(注意后缀里有win_amd64这个字段, 不要下载linux版本)

我安装了
Name: mmcv-full
Version: 1.1.5
Summary: OpenMMLab Computer Vision Foundation
Home-page: https://github.com/open-mmlab/mmcv
Author: MMCV Authors
Author-email: openmmlab@gmail.com
License: UNKNOWN
Location: c:\users\not found\appdata\local\programs\python\python38\lib\site-packages
Requires: opencv-python, yapf, pyyaml, addict, regex, numpy
Required-by: mmedit

但还是提示
Traceback (most recent call last):
  File "demo/motion_imitate.py", line 10, in <module>
    from iPERCore.services.run_imitator import run_imitator
  File "e:\ipercore\iPERCore\services\run_imitator.py", line 4, in <module>
    from iPERCore.models import ModelsFactory
  File "e:\ipercore\iPERCore\models\__init__.py", line 2, in <module>
    from .flowcomposition import FlowComposition
  File "e:\ipercore\iPERCore\models\flowcomposition.py", line 7, in <module>
    from iPERCore.tools.human_digitalizer.renders import SMPLRenderer
  File "e:\ipercore\iPERCore\tools\human_digitalizer\renders\__init__.py", line 1, in <module>
    from .nmr import SMPLRenderer
  File "e:\ipercore\iPERCore\tools\human_digitalizer\renders\nmr.py", line 6, in <module>
    import neural_renderer as nr
  File "C:\Users\Not found\AppData\Local\Programs\Python\Python38\lib\site-packages\neural_renderer\__init__.py", line 3, in <module>
    from .load_obj import load_obj
  File "C:\Users\Not found\AppData\Local\Programs\Python\Python38\lib\site-packages\neural_renderer\load_obj.py", line 9, in <module>
    import neural_renderer.cuda.load_textures as load_textures_cuda
ImportError: DLL load failed while importing load_textures: 找不到指定的模块。
